const express = require("express");
const cors = require("cors");
const path = require("path");

require("dotenv").config();


// ============================================================
// APP
// ============================================================

const app = express();

app.use(cors());
app.use(express.json());


// ============================================================
// PYTHON AI SERVER
// ============================================================

const AI_SERVER_URL =
  process.env.AI_SERVER_URL || "http://127.0.0.1:5000";


// ============================================================
// FRONTEND
// ============================================================

app.use(
  express.static(__dirname)
);


// ============================================================
// HEALTH CHECK
// ============================================================

app.get("/health", async (req, res) => {

  try {

    const response = await fetch(
      `${AI_SERVER_URL}/health`
    );

    if (!response.ok) {

      return res.status(503).json({
        status: "error",
        message: "Python AI server is unavailable."
      });

    }

    const data = await response.json();

    return res.json({
      status: "ok",
      aiServer: data
    });

  } catch (error) {

    console.error(
      "AI health check error:",
      error.message
    );

    return res.status(503).json({
      status: "error",
      message: "Python AI server is unavailable."
    });

  }

});


// ============================================================
// CHAT API
// ============================================================

app.post("/api/chat", async (req, res) => {

  try {

    const message =
      typeof req.body.message === "string"
        ? req.body.message.trim()
        : "";

    const history =
      Array.isArray(req.body.history)
        ? req.body.history
        : [];


    // --------------------------------------------------------
    // Validate message
    // --------------------------------------------------------

    if (!message) {

      return res.status(400).json({
        error: "Message is required."
      });

    }


    console.log(
      "\n========================================"
    );

    console.log(
      "CUSTOMER:",
      message
    );


    // --------------------------------------------------------
    // Send request to Python AI
    // --------------------------------------------------------

    const response = await fetch(
      `${AI_SERVER_URL}/chat`,
      {
        method: "POST",

        headers: {
          "Content-Type": "application/json"
        },

        body: JSON.stringify({
          message,
          history
        })
      }
    );


    // --------------------------------------------------------
    // Python server error
    // --------------------------------------------------------

    if (!response.ok) {

      const errorText =
        await response.text();

      console.error(
        "Python AI error:",
        errorText
      );

      return res.status(502).json({
        error:
          "The SOFT FLOWER Intelligence Assistant is temporarily unavailable."
      });

    }


    // --------------------------------------------------------
    // Read AI response
    // --------------------------------------------------------

    const data =
      await response.json();


    console.log(
      "GENERATED BY:",
      data.generatedBy
    );

    console.log(
      "AI:",
      data.reply
    );

    console.log(
      "========================================\n"
    );


    // --------------------------------------------------------
    // Return response to website
    // --------------------------------------------------------

    return res.json({

      reply:
        data.reply,

      generatedBy:
        data.generatedBy || "soft-flower-ai"

    });

  }


  catch (error) {

    console.error(
      "CHAT API ERROR:",
      error.message
    );


    return res.status(500).json({

      error:
        "The SOFT FLOWER Intelligence Assistant is temporarily unavailable."

    });

  }

});


// ============================================================
// ROOT
// ============================================================

app.get("/", (req, res) => {

  res.sendFile(
    path.join(
      __dirname,
      "index.html"
    )
  );

});


// ============================================================
// START SERVER
// ============================================================

const PORT =
  process.env.PORT || 3000;


app.listen(
  PORT,
  "0.0.0.0",
  () => {

    console.log(
      "\n========================================"
    );

    console.log(
      "SOFT FLOWER WEBSITE SERVER"
    );

    console.log(
      "========================================"
    );

    console.log(
      `Website: http://127.0.0.1:${PORT}`
    );

    console.log(
      `Python AI: ${AI_SERVER_URL}`
    );

    console.log(
      "Gemini: DISABLED"
    );

    console.log(
      "========================================\n"
    );

  }
);